In [1]:
import numpy as np

In [3]:
#forming matrices
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[10,20],[30,40],[50,60]])
print(a)
print(b)

[[1 2]
 [3 4]
 [5 6]]
[[10 20]
 [30 40]
 [50 60]]


In [5]:
#matrix addition
np.add(a,b)
#a+b also works

array([[11, 22],
       [33, 44],
       [55, 66]])

In [8]:
#matrix subtraction
np.subtract(a,b)
# a-b also works

array([[ -9, -18],
       [-27, -36],
       [-45, -54]])

In [9]:
p = np.array([[1,2],[3,4],[5,6]])
q = np.array([[2,3],[4,5]])
print(p)
print(q)

[[1 2]
 [3 4]
 [5 6]]
[[2 3]
 [4 5]]


In [11]:
#matrix multiplication
np.dot(p,q)

array([[10, 13],
       [22, 29],
       [34, 45]])

In [13]:
#determinanr
np.linalg.det(q)

-2.0

In [15]:
#inverse
np.linalg.inv(q)

array([[-2.5,  1.5],
       [ 2. , -1. ]])