In [1]:
import numpy as np

In [2]:
#vectors
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [3]:
#vector addition
v1+v2

array([5, 7, 9])

In [4]:
#vector subtraction
v1-v2

array([-3, -3, -3])

In [5]:
#scalr multiplied with vector
5 * v1

array([ 5, 10, 15])

In [6]:
#length of vector
np.linalg.norm(v1)

3.7416573867739413

In [7]:
#dot product
np.dot(v1,v2)

32